// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bidirectionalstream.proto

/*
Package bidirectionalpb is a generated protocol buffer package.

It is generated from these files:
	bidirectionalstream.proto

It has these top-level messages:
	Greeting
	GreetEveryoneRequest
	GreetEveryoneResponse
*/
package bidirectionalpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Greeting struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
}

func (m *Greeting) Reset()                    { *m = Greeting{} }
func (m *Greeting) String() string            { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()               {}
func (*Greeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetEveryoneRequest struct {
	Greeting *Greeting `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *GreetEveryoneRequest) Reset()                    { *m = GreetEveryoneRequest{} }
func (m *GreetEveryoneRequest) String() string            { return proto.CompactTextString(m) }
func (*GreetEveryoneRequest) ProtoMessage()               {}
func (*GreetEveryoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GreetEveryoneRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetEveryoneResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *GreetEveryoneResponse) Reset()                    { *m = GreetEveryoneResponse{} }
func (m *GreetEveryoneResponse) String() string            { return proto.CompactTextString(m) }
func (*GreetEveryoneResponse) ProtoMessage()               {}
func (*GreetEveryoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GreetEveryoneResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetEveryoneRequest)(nil), "greet.GreetEveryoneRequest")
	proto.RegisterType((*GreetEveryoneResponse)(nil), "greet.GreetEveryoneResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GreetService service

type GreetServiceClient interface {
	// Server Stream
	GreetEveryone(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryoneClient, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) GreetEveryone(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryoneClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GreetService_serviceDesc.Streams[0], c.cc, "/greet.GreetService/GreetEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetEveryoneClient{stream}
	return x, nil
}

type GreetService_GreetEveryoneClient interface {
	Send(*GreetEveryoneRequest) error
	Recv() (*GreetEveryoneResponse, error)
	grpc.ClientStream
}

type greetServiceGreetEveryoneClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetEveryoneClient) Send(m *GreetEveryoneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceGreetEveryoneClient) Recv() (*GreetEveryoneResponse, error) {
	m := new(GreetEveryoneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GreetService service

type GreetServiceServer interface {
	// Server Stream
	GreetEveryone(GreetService_GreetEveryoneServer) error
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_GreetEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).GreetEveryone(&greetServiceGreetEveryoneServer{stream})
}

type GreetService_GreetEveryoneServer interface {
	Send(*GreetEveryoneResponse) error
	Recv() (*GreetEveryoneRequest, error)
	grpc.ServerStream
}

type greetServiceGreetEveryoneServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetEveryoneServer) Send(m *GreetEveryoneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceGreetEveryoneServer) Recv() (*GreetEveryoneRequest, error) {
	m := new(GreetEveryoneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetEveryone",
			Handler:       _GreetService_GreetEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bidirectionalstream.proto",
}

func init() { proto.RegisterFile("bidirectionalstream.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4b, 0xc6, 0x20,
	0x14, 0x86, 0x33, 0xa8, 0xb6, 0x53, 0x31, 0x92, 0x82, 0xd5, 0x0a, 0xc2, 0xab, 0x41, 0x30, 0x6a,
	0xfd, 0x83, 0xa2, 0xba, 0x8b, 0x58, 0x77, 0xdd, 0x94, 0x5b, 0x27, 0x11, 0xa6, 0x2e, 0xb5, 0x41,
	0xff, 0x3e, 0x66, 0x19, 0xdf, 0xc6, 0x77, 0xa7, 0xef, 0xa3, 0xcf, 0x7b, 0x38, 0x70, 0xdc, 0xca,
	0x77, 0x69, 0xb1, 0xf3, 0xd2, 0x68, 0xde, 0x3b, 0x6f, 0x91, 0xab, 0x6a, 0xb0, 0xc6, 0x1b, 0xba,
	0x25, 0x2c, 0xa2, 0x67, 0xf7, 0x90, 0x3c, 0x4c, 0x07, 0xa9, 0x05, 0x3d, 0x03, 0xf8, 0x90, 0xd6,
	0xf9, 0x57, 0xcd, 0x15, 0xe6, 0xe4, 0x9c, 0x94, 0x69, 0x93, 0x86, 0xe4, 0x91, 0x2b, 0xa4, 0x05,
	0xa4, 0x3d, 0x8f, 0x74, 0x33, 0xd0, 0x64, 0x0a, 0x26, 0xc8, 0x6e, 0xe1, 0x30, 0x78, 0xee, 0x46,
	0xb4, 0xdf, 0x46, 0x63, 0x83, 0x9f, 0x5f, 0xe8, 0x3c, 0xbd, 0x80, 0x44, 0xfc, 0xf9, 0x83, 0x71,
	0xb7, 0xce, 0xaa, 0x10, 0x54, 0xb1, 0xb6, 0xf9, 0x7f, 0xc0, 0xae, 0xe0, 0x68, 0x21, 0x71, 0x83,
	0xd1, 0x0e, 0x69, 0x0e, 0x3b, 0x0a, 0x9d, 0xe3, 0x22, 0x8e, 0x15, 0xaf, 0xf5, 0x1b, 0xec, 0x85,
	0x2f, 0xcf, 0x68, 0x47, 0xd9, 0x21, 0x7d, 0x82, 0xfd, 0x99, 0x82, 0x16, 0xab, 0x75, 0x8b, 0xe9,
	0x4e, 0x4e, 0xd7, 0xc3, 0xdf, 0x56, 0xb6, 0x51, 0x92, 0x4b, 0x72, 0x73, 0xf0, 0x92, 0xcd, 0xb6,
	0x38, 0xb4, 0xed, 0x76, 0x58, 0xe1, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x26, 0x26,
	0x26, 0x5f, 0x01, 0x00, 0x00,
}
